name: 'prepare-vulns-secrets-env'
description: 'prepare everything needed to run vulnerability and secrets checks'
runs:
  using: 'composite'
  steps:
    - name: install dependencies
      shell: bash
      run:  |
        sudo apt update
        sudo apt-get install -y moreutils python3-pip
        pip3 install jinja2

    - name: prepare data.json for pr and slack comments
      shell: bash
      run:  |
        jq -n \
          --arg repo "${{github.repository}}" \
          --arg headRefPush "${GITHUB_REF}" \
          --arg headRefPR "${{github.head_ref}}" \
          --arg actor "${{github.actor}}" \
          --arg eventName "${{github.event_name}}" \
          --arg eventNumber "${{github.event.number}}" \
          --arg commitSha "${{github.sha}}" \
          '{github: {repo: $repo, headRefPush: $headRefPush, headRefPR: $headRefPR, actor: $actor, eventName: $eventName, eventNumber: $eventNumber, commitSha: $commitSha}}' \
          > data.json

    - name: install trivy
      uses: aquasecurity/setup-trivy@v0.2.1
      with:
        version: v0.56.2
