---
name: build-image
description: |
  The action is launched in the PRs opened by the Renovate bot
  when one or more of the tags `build:dev`, `build:staging`, `build:prod` are added,
  and does the following:
    - export environment variables from required files
    - extract tag by image digest specified in Dockerfile
    - build and publish image with received tag and `latest` tag
    - create a json file with variables for the jinja template and upload it as an artifact
    - send a notification to slack channel

inputs:
  context:
    description: folder with files required to build docker image
    required: true
  dockerfile:
    description: dockerfile name
    required: true
  dockerhub_registry_url:
    description: dockerhub api registry url
    required: false
    default: https://registry.hub.docker.com/v2
  dockerhub_token_url:
    description: dockerhub api token url
    required: false
    default: https://hub.docker.com/v2/users/login/
  dockerhub_token:
    description: token for read-only access to dockerhub
    required: false
    default: ''
  dockerhub_username:
    description: username for read-only access to dockerhub
    required: false
    default: ''
  environment:
    description: |
      the environment for which the image will be built:
      `dev`, `prod`, `staging`
    required: true
  slack_webhook_url:
    description: |
      CI slack channel webhook url for sending build notifications
      https://api.slack.com/apps/A01LM626QTZ/incoming-webhooks
    required: true

runs:
  using: composite
  steps:
    - name: Export environment variables from .env files
      id: env-vars
      uses: aarcangeli/load-dotenv@v1
      with:
        filenames: |
          .env
          .env.${{ inputs.environment }}
          ${{ inputs.context }}/.env
          ${{ inputs.context }}/.env.${{ inputs.environment }}
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: ${{ env.aws_region }}
        role-to-assume: ${{ env.aws_gha_role }}
    - name: Detect ECR type
      shell: bash
      run: |
        echo "ECR_TYPE=private" >> $GITHUB_ENV
        if [[ "${{ env.ecr_repository_uri }}" == public.ecr.aws* ]]; then
          echo "ECR_TYPE=public" >> $GITHUB_ENV
        fi
    - name: Login to AWS ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v2.0.1
      with:
        registry-type: ${{ env.ECR_TYPE }}
    - name: Get DockerHub API token
      id: dockerhub-token
      shell: bash
      run: |
        set -euo pipefail
        # get dockerhub authorization token
        # if the dockerhub username and password isn't passed, then we get the following response:
        # {"detail":"Incorrect authentication credentials"}
        # and in that case it's replaced with an empty value
        token=$(curl -X POST \
          -s -H "Content-Type: application/json" \
          -d "{\"username\": \"${{ inputs.dockerhub_username }}\", \"password\": \"${{ inputs.dockerhub_token }}\"}" \
          ${{ inputs.dockerhub_token_url }} | jq -r '.token // empty')
        echo "token=${token}" >> $GITHUB_OUTPUT
    - name: Find the tag for a given image digest in Dockerhub
      id: tag
      shell: bash
      run: |
        set -euo pipefail
        target_digest=$(grep '^ARG IMAGE_SHA=' ${{ inputs.context }}/${{ inputs.dockerfile }} | cut -d= -f2)
        echo "Image digest: ${target_digest}"

        # find a tag whose digest matches the given one and which is not called 'latest'
        page=1
        block_size=50
        url="${{ inputs.dockerhub_registry_url }}/repositories/${docker_repository}/tags"
        total_tags=$(curl -s ${url} | jq -r '.count')
        tag=""
        while [[ -z ${tag} && ${page} -le ${total_tags} ]]; do
          # the authorization token is added to the request if it has a non-empty value
          tag=$(curl \
            -s ${token:+-H "Authorization: JWT ${{ steps.dockerhub-token.outputs.token }}"} \
            "${url}?page_size=${block_size}&page=${page}" \
            | jq -r --arg digest "${target_digest}" \
            '.results // [] | .[] | select(.digest == $digest and .name != "latest") | .name')
          ((page+=1))
        done
        if [ -z ${tag} ]; then
          echo "❗️Tag for digest ${target_digest} not found"
          exit 1
        fi
        echo "✅ Matching tag found: ${tag}"
        echo "image_tag=$tag" >> $GITHUB_OUTPUT
    - name: Determine Dockerfile suffix
      id: dockerfile-suffix
      shell: bash
      run: |
        filename="${{ inputs.dockerfile }}"
        # runner-jammy.Dockerfile → jammy
        base=$(basename "$filename" .Dockerfile)
        if [[ "$base" == *"-"* ]]; then
          suffix="-${base#*-}"
        else
          suffix=""
        fi
        echo "suffix=$suffix" >> $GITHUB_OUTPUT
    - name: Build and push docker image
      id: build-image
      uses: docker/build-push-action@v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        platforms: ${{ env.platforms }}
        push: true
        tags: |
          ${{ env.ecr_repository_uri }}:${{ steps.tag.outputs.image_tag }}${{ steps.dockerfile-suffix.outputs.suffix }},
          ${{ env.ecr_repository_uri }}:latest${{ steps.dockerfile-suffix.outputs.suffix }}
    - name: Configure settings for PR comment
      id: pr-data
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        set -euo pipefail
        # create json file name with variables for pr comment using context name
        # `buildpacks/backend/builder` --> `buildpacks-backend-builder`
        artifact="${{ inputs.context }}"
        artifact="${artifact//\//-}-${{ inputs.environment }}"
        echo "artifact=${artifact}" >> $GITHUB_OUTPUT
        # create a file with variables for the pr comment template
        # example:
        # {
        #   aws_account: XXXXXXXXXXXX,
        #   aws_region: us-east-1,
        #   images: [{
        #     ecr_repo: project/prod/backend/buildpacks/builder,
        #     digest: sha256:1244e81fbe4bec9f97ac81483022d63386a8ad4abb461b5e307cc0c9718847dd
        #   }]
        # }
        jq -n \
          --arg aws_account "${{ env.aws_account }}" \
          --arg aws_region "${{ env.aws_region }}" \
          --arg ecr_repo "${{ env.ecr_repository_name }}" \
          --arg digest "${{ steps.build-image.outputs.digest }}" \
            '{
              images: [{
                aws_account: $aws_account,
                aws_region: $aws_region,
                ecr_repo: $ecr_repo,
                digest: $digest
              }]
            }' > ${artifact}.json
    - name: Upload pr-comment-data.json as artifact
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.pr-data.outputs.artifact }}
        path: ${{ steps.pr-data.outputs.artifact }}.json
    - name: Configure settings for slack message
      id: slack-data
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        set -euo pipefail
        if ${{ contains(steps.*.outcome, 'failure') }}; then
          echo "color=cc0000" >> $GITHUB_OUTPUT
          echo "message=😞 The build of *${{ inputs.context }}* image with version *${{ steps.tag.outputs.image_tag }}* failed." >> $GITHUB_OUTPUT
        else
          echo "color=28a745" >> $GITHUB_OUTPUT
          echo "message=The build of *${{ inputs.context }}* image with version *${{ steps.tag.outputs.image_tag }}* was successful! :rocket:" >> $GITHUB_OUTPUT
        fi
    - name: Send notification to slack
      if: ${{ !cancelled() }}
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.slack_webhook_url }}
        webhook-type: incoming-webhook
        payload: |-
          attachments:
            - color: "${{ steps.slack-data.outputs.color }}"
              author_name: ${{ github.actor }}
              author_link: https://github.com/${{ github.actor }}
              author_icon: https://github.com/${{ github.actor }}.png
              fields:
                - short: false
                  value: "${{ steps.slack-data.outputs.message }}"
                - title: Environment
                  short: true
                  value: ${{ inputs.environment }}
                - title: Pull request
                  short: true
                  value: <https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|#${{ github.event.number }}>
                - title: Action URL
                  short: true
                  value: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>
                - title: Repository
                  short: true
                  value: <https://github.com/${{ github.repository }}/blob/main/${{ inputs.context }}/${{ inputs.dockerfile }}|${{ github.repository }}>
