import argparse
import asyncio
import os
import re
from dataclasses import dataclass
from typing import Set, List

from agents import Agent, Runner
from agents.mcp import MCPServerStdio
from github import Auth, Github, Commit

AI_MARKER = '**generated by'

@dataclass
class Summary:
    """
    Represents a Markdown summary report for a PR.
    Attributes:
        analysis (str): AI-generated analysis text.
        jira_issues (Set[str]): Set of JIRA issue identifiers.
        jira_url (str): Base URL of the JIRA system.
        model (str): Model used to generate the analysis.
    """
    analysis: str
    jira_issues: Set[str]
    jira_url: str
    model: str

    def __str__(self) -> str:
        """
        Generates a Markdown string representation of the summary.
        Returns:
            str: Formatted Markdown string including tasks, analysis,
            and model info.
        """
        jira_links = [
            f'[{issue}]({self.jira_url}/browse/{issue})'
            for issue in sorted(self.jira_issues)
        ]
        tasks = (
            f'Task: {", ".join(jira_links) if jira_links else "No JIRA issues referenced"}'
        )

        return (
            '### Summary\n\n'
            f'{tasks}\n\n'
            f'{self.analysis}\n\n'
            f'**generated by {self.model}**\n'
        )

@dataclass
class AgentConfig:
    """
    Configuration for the PR summary agent.
    Attributes:
        github_client (Github): Authenticated GitHub client instance.
        jira_url (str): Base URL of the JIRA instance.
        model (str): Model name to use for analysis (e.g. "gpt-5").
        openai_prompt (str): Prompt template passed to the model.
        pr_number (int): Pull request number to process.
        repo_path (str): Local repository path used by MCP server.
        repository (str): GitHub repository in format "owner/repo".
    """
    github_client: Github
    jira_url: str
    model: str
    openai_prompt: str
    pr_number: int
    repo_path: str
    repository: str

class PrSummaryAgent:
    """
    Agent responsible for generating a PR summary.
    """
    def __init__(self, config: AgentConfig):
        """Initialize the PR summary agent.
        Args:
            config (AgentConfig): Configuration object for the agent.
        """
        self.config = config

    async def run(self) -> Summary:
        """
        Generate a summary for the configured pull request and update PR body.
        Preserves any human-written text found after the Task: line (first run)
        or after the AI marker (subsequent runs).
        Returns:
            Summary: A dataclass containing the AI analysis, extracted JIRA
            issues, JIRA URL, and model information.
        Raises:
            github.GithubException: If fetching the repository or PR fails.
            ValueError: If the OpenAI prompt is missing or malformed.
        """
        repository = self.config.github_client.get_repo(self.config.repository)
        pull_request = repository.get_pull(self.config.pr_number)

        files = list(pull_request.get_files())
        commits = list(pull_request.get_commits())
        jira_issues = extract_jira_issues(commits)

        available_labels = get_taggable_labels(repository)

        all_files, code_changes = [], []
        # Limit code changes to avoid exceeding the model's context window
        max_code_changes_chars = 900000
        code_changes_size = 0
        for f in files:
            all_files.append(f.filename)
            if code_changes_size >= max_code_changes_chars:
                continue
            patch = f.patch or ''
            entry = f"{f.filename} ({f.status}): {patch}"
            if code_changes_size + len(entry) > max_code_changes_chars:
                code_changes.append('... (remaining patches truncated due to size limit)')
                code_changes_size = max_code_changes_chars
                continue
            code_changes.append(entry)
            code_changes_size += len(entry)

        full_prompt = self.config.openai_prompt.format(
            all_files='\n'.join(all_files),
            code_changes='\n'.join(code_changes),
            available_labels=', '.join(available_labels),
        )

        # uvx may take time to download mcp-server-git.
        # increased timeout prevent flaky McpError: Timed out failures
        async with MCPServerStdio(
            cache_tools_list=True,
            params={
                'command': 'uvx',
                'args': ['mcp-server-git', '--repository', str(self.config.repo_path)],
            },
            client_session_timeout_seconds=30,
        ) as server:
            agent = Agent(
                name='PR Summary Agent',
                instructions='You are a helpful assistant that generates pull request summaries.',
                mcp_servers=[server],
                model=self.config.model,
            )
            result = await Runner.run(starting_agent=agent, input=full_prompt)
            raw_output = result.final_output.strip()

        labels_to_apply = []
        if available_labels and 'LABELS:' in raw_output:
            last_line = raw_output.rsplit('LABELS:', 1)[-1].strip().splitlines()[0]
            labels_to_apply = [l.strip() for l in last_line.split(',') if l.strip() in available_labels]
            analysis = raw_output[:raw_output.rfind('LABELS:')].strip()
        else:
            analysis = raw_output

        summary = Summary(analysis, jira_issues, self.config.jira_url, self.config.model)
        new_body = str(summary) + self._extract_human_text(pull_request.body or '')
        pull_request.edit(body=new_body)
        if labels_to_apply:
            pull_request.add_to_labels(*labels_to_apply)

        return summary

    def _extract_human_text(self, body: str) -> str:
        """
        Extract human-written text from the PR body to preserve it.
        On subsequent runs: returns text after the AI marker line.
        On first run: returns text after the Task: line (developer's description),
        stopping at HTML comments.
        Returns:
            str: Human-written text to append after the new AI summary, or empty string.
        """
        if AI_MARKER in body:
            after_marker = body[body.index(AI_MARKER):]
            human_text = after_marker[after_marker.index('\n'):].strip()
            return ('\n\n' + human_text) if human_text else ''

        # First run: extract text after Task: line, stopping at <!-- comments
        lines = body.splitlines()
        human_lines = []
        after_task = False
        for line in lines:
            if re.match(r'(?i)(task|jira):', line):
                after_task = True
                continue
            if not after_task:
                continue
            if line.startswith('<!--'):
                break
            human_lines.append(line)

        human_text = '\n'.join(human_lines).strip()
        return ('\n\n' + human_text) if human_text else ''

def get_taggable_labels(repository) -> List[str]:
    """Return labels with env=, c/, or p/ prefixes from the repository."""
    return [
        label.name for label in repository.get_labels()
        if re.match(r'^(env=|c/|p/)', label.name)
    ]

def extract_jira_issues(commits: List[Commit]) -> Set[str]:
    """
    Extract JIRA issue numbers from commit messages.
    Args:
        commits (List[Commit]): List of GitHub commit objects
            (from PyGithub) associated with the pull request.

    Returns:
        Set[str]: Unique JIRA issue keys found in commit messages.
    """
    jira_pattern = re.compile(r'[A-Z]+-\d+')
    issues = set()
    for commit in commits:
        matches = jira_pattern.findall(commit.commit.message)
        issues.update(matches)
    return issues

def main():
    """
    Main function that parses command line arguments and initiates PR summary generation.
    """
    parser = argparse.ArgumentParser(description='Generate PR summary using MCP Git')
    parser.add_argument(
        '--jira-url',
        default='https://saritasa.atlassian.net',
        help='Base URL for Jira'
    )
    parser.add_argument(
        '--model',
        default='gpt-5',
        help='OpenAI model to use'
    )
    parser.add_argument(
        '--pr-number',
        type=int,
        required=True,
        help='GitHub PR number'
    )
    args = parser.parse_args()

    github_client = Github(auth=Auth.Token(os.environ['GITHUB_TOKEN']))

    config = AgentConfig(
        github_client=github_client,
        jira_url=args.jira_url,
        model=args.model,
        openai_prompt=os.environ.get('OPENAI_PROMPT'),
        pr_number=args.pr_number,
        repo_path=os.environ['REPO_PATH'],
        repository=os.environ['REPOSITORY'],
    )

    pr_agent = PrSummaryAgent(config)
    asyncio.run(pr_agent.run())

if __name__ == '__main__':
    main()
