import argparse
import asyncio
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Set, List

from agents import Agent, Runner
from agents.mcp import MCPServerStdio
from github import Auth, Github, Commit

@dataclass
class Summary:
    """
    Represents a Markdown summary report for a PR.
    Attributes:
        analysis (str): AI-generated analysis text.
        jira_issues (Set[str]): Set of JIRA issue identifiers.
        jira_url (str): Base URL of the JIRA system.
        model (str): Model used to generate the analysis.
    """
    analysis: str
    jira_issues: Set[str]
    jira_url: str
    model: str

    def __str__(self) -> str:
        """
        Generates a Markdown string representation of the summary.
        Returns:
            str: Formatted Markdown string including tasks, analysis,
            and model info.
        """
        jira_links = [
            f'[{issue}]({self.jira_url}/browse/{issue})'
            for issue in sorted(self.jira_issues)
        ]
        tasks = (
            f'Task: {", ".join(jira_links) if jira_links else "No JIRA issues referenced"}'
        )

        return (
            '### Summary\n\n'
            f'{tasks}\n\n'
            f'{self.analysis}\n\n'
            f'**generated by {self.model}**\n'
        )

@dataclass
class AgentConfig:
    """
    Configuration for the PR summary agent.
    Attributes:
        github_client (Github): Authenticated GitHub client instance.
        jira_url (str): Base URL of the JIRA instance.
        model (str): Model name to use for analysis (e.g. "gpt-5").
        openai_prompt (str): Prompt template passed to the model.
        output_path (Path): Path where the generated summary will be written.
        pr_number (int): Pull request number to process.
        repo_path (Path): Local repository path used by MCP server.
        repository (str): GitHub repository in format "owner/repo".
    """
    github_client: Github
    jira_url: str
    model: str
    openai_prompt: str
    output_path: Path
    pr_number: int
    repo_path: Path
    repository: str

class PrSummaryAgent:
    """
    Agent responsible for generating a PR summary.
    """
    def __init__(self, config: AgentConfig):
        """Initialize the PR summary agent.
        Args:
            config (AgentConfig): Configuration object for the agent.
        """
        self.config = config

    async def run(self) -> Summary:
        """
        Generate a summary for the configured pull request.
        Fetches the PR files and commits via GitHub API, extracts JIRA issue
        keys, builds a prompt, and runs the agent with MCP server to produce
        an AI-generated analysis.
        Returns:
            Summary: A dataclass containing the AI analysis, extracted JIRA
            issues, JIRA URL, and model information.
        Raises:
            github.GithubException: If fetching the repository or PR fails.
            ValueError: If the OpenAI prompt is missing or malformed.
        """
        repository = self.config.github_client.get_repo(self.config.repository)
        pull_request = repository.get_pull(self.config.pr_number)

        files = list(pull_request.get_files())
        commits = list(pull_request.get_commits())
        jira_issues = extract_jira_issues(commits)

        all_files, code_changes = [], []
        # Limit code changes to avoid exceeding the model's context window
        max_code_changes_chars = 900000
        code_changes_size = 0
        for f in files:
            all_files.append(f.filename)
            if code_changes_size >= max_code_changes_chars:
                continue
            patch = f.patch or ''
            entry = f"{f.filename} ({f.status}): {patch}"
            if code_changes_size + len(entry) > max_code_changes_chars:
                code_changes.append('... (remaining patches truncated due to size limit)')
                code_changes_size = max_code_changes_chars
                continue
            code_changes.append(entry)
            code_changes_size += len(entry)

        prompt_values = {
            'all_files': '\n'.join(all_files),
            'code_changes': '\n'.join(code_changes),
        }

        full_prompt = self.config.openai_prompt.format(**prompt_values)

        # uvx may take time to download mcp-server-git.
        # increased timeout prevent flaky McpError: Timed out failures
        async with MCPServerStdio(
            cache_tools_list=True,
            params={
                'command': 'uvx',
                'args': ['mcp-server-git', '--repository', str(self.config.repo_path)],
            },
            client_session_timeout_seconds=30,
        ) as server:
            agent = Agent(
                name='PR Summary Agent',
                instructions='You are a helpful assistant that generates pull request summaries.',
                mcp_servers=[server],
                model=self.config.model,
            )
            result = await Runner.run(starting_agent=agent, input=full_prompt)
            analysis = result.final_output.strip()

        summary = Summary(analysis, jira_issues, self.config.jira_url, self.config.model)
        self.config.output_path.parent.mkdir(parents=True, exist_ok=True)
        self.config.output_path.write_text(str(summary), encoding='utf-8')

        return summary

def extract_jira_issues(commits: List[Commit]) -> Set[str]:
    """
    Extract JIRA issue numbers from commit messages.
    Args:
        commits (List[Commit]): List of GitHub commit objects
            (from PyGithub) associated with the pull request.

    Returns:
        Set[str]: Unique JIRA issue keys found in commit messages.
    """
    jira_pattern = re.compile(r'[A-Z]+-\d+')
    issues = set()
    for commit in commits:
        matches = jira_pattern.findall(commit.commit.message.upper())
        issues.update(matches)
    return issues

def main():
    """
    Main function that parses command line arguments and initiates PR summary generation.
    """
    parser = argparse.ArgumentParser(description='Generate PR summary using MCP Git')
    parser.add_argument(
        '--jira-url',
        default='https://saritasa.atlassian.net',
        help='Base URL for Jira'
    )
    parser.add_argument(
        '--model',
        default='gpt-5',
        help='OpenAI model to use'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default='summary.md',
        help='Output file path'
    )
    parser.add_argument(
        '--pr-number',
        type=int,
        required=True,
        help='GitHub PR number'
    )
    args = parser.parse_args()

    github_client = Github(auth=Auth.Token(os.environ['GITHUB_TOKEN']))

    config = AgentConfig(
        github_client=github_client,
        jira_url=args.jira_url,
        model=args.model,
        openai_prompt=os.environ.get('OPENAI_PROMPT'),
        output_path=args.output,
        pr_number=args.pr_number,
        repo_path=Path(os.environ['REPO_PATH']),
        repository=os.environ['REPOSITORY'],
    )

    pr_agent = PrSummaryAgent(config)
    asyncio.run(pr_agent.run())

if __name__ == '__main__':
    main()
