# ==============================================================================
# Whenever there is a new PR, add a small description of it to the CHANGELOG.md file
#
# 1. Add date
# 2. If date already exist, it should not duplicate it, append the content to the already defined date
# 3. If PR number already exist in changelog, then it should exit as it was already added before
# 4. Read the PR title and add that as the changelog entry explanation
# 5.a If `run_in_base_branch` is false then commit will be added directly to open PR (It will use action context to get the PR)
# 6.a No additional variable/secret configuration is needed, commit author will be saritasa-renovatebot
# 5.b If `run_in_base_branch` is true then commit will be added to base branch (probably main/develop) after PR is merged
# 6.b `github_app_id` `github_app_private_key` `github_app_name` must be configured to use saritasa-changelog Github app (https://github.com/organizations/saritasa-nest/settings/apps/saritasa-changelog)
# 7.b `Do not allow bypassing the above settings config` must be disabled to allow Admins to bypass branch protections
# ==============================================================================

name: changelog-update
description: this check finds the unencrypted secrets in the code
inputs:
  environment:
    description: The environment in which this new PR is making a modification
    default: dev
  changelog_path:
    description: The path of the CHANGELOG file
    default: CHANGELOG.md
  changelog_create_if_missing:
    description: Create a new CHANGELOG file if it does not exist
    default: "enabled"
  run_in_base_branch:
    description: If true, Changelog file will be modified in base branch of PR. (Instead of default head branch)
    default: 'true'
  github_app_id:
    description: Github App ID
    default: ""
  github_app_private_key:
    description: Github App Private key
    default: ""
  github_app_name:
    description: Github App name (used to set up commits author). Use RenovateBot as default
    default: "saritasa-renovatebot"

runs:
  using: composite
  steps:
    - name: Check that Renovate creds are set if `run_in_base_branch` is true
      shell: bash
      if: inputs.run_in_base_branch == 'true' && (inputs.github_app_id == '' || inputs.github_app_private_key == '')
      run: |
        echo "Error: github_app_id and github_app_private_key must be set when run_in_base_branch is true."
        exit 1
    - uses: actions/create-github-app-token@v1
      if: inputs.run_in_base_branch == 'true'
      id: app-token
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_app_private_key }}
    - uses: actions/checkout@v4
      with:
        ref: ${{ (inputs.run_in_base_branch == 'true' && github.base_ref) || github.head_ref }}
        token: ${{ steps.app-token.outputs.token || github.token }}
    - name: add changelog entry
      env:
        repository: ${{ github.repository }}
        pr_number: ${{ github.event.pull_request.number }}
        pr_title: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        python3 ${{ github.action_path }}/scripts/changelog.py --repository '${{ env.repository }}' --pr-number ${{ env.pr_number }} --pr-title "${{ env.pr_title }}" --environment "${{ inputs.environment }}" --changelog-path ${{ inputs.changelog_path }} --create-if-missing ${{ inputs.changelog_create_if_missing }}
        cat CHANGELOG.md
    - name: commit and push
      shell: bash
      run: |
        git add CHANGELOG.md
        git config user.name '${{ inputs.github_app_name }}[bot]'
        git config user.email '${{ inputs.github_app_name }}[bot]@users.noreply.github.com'
        git commit -m "feat: update CHANGELOG"
        git push
