name: 'fastlane'
description: 'Runs fastlane ci for ios platformwith target'
inputs:
  environment:
    description: "According .env file provided in fastlane folder, usually one of [local, dev, staging, prod]"
    required: true
  target:
    description: "Build target declared in Fastfile, usually one of [build, release]"
    required: true
  # Optional
  ruby_version:
    required: false
    default: '3.0'
  bundler_version:
    description: Option for 'gem install` command
    required: false
    default: '2.2.16'
  # iOS
  certificate:
    description: "Certificate for ios sign"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # Setup ruby on github hosted machines, step fails on self-hosted macjenkins
    - name: Setup ruby
      if: ${{ runner.name == 'Hosted Agent' }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    # Setup dependencies for fastlane package from Gemfile
    - name: Setup dependencies
      shell: bash
      run: |
        gem install bundler:${{ inputs.bundler_version }}
        bundle install --jobs 4 --retry 3
    # "Populates 'ci' keychain with provided external cert for code sign, see more: https://blog.codemagic.io/how-to-code-sign-publish-ios-apps/"
    - name: Update ci keychain for iOS
      if: ${{ inputs.certificate != ''}}
      shell: bash
      run: |
        echo -n "${{ inputs.certificate }}" | base64 --decode --output fastlane/cert.certificate
        bundle exec fastlane ios update_keychain
    # Execute lane from Fastfile
    - name: Execute fastlane target
      shell: bash
      run: bundle exec fastlane ios ${{ inputs.target }} --env ${{ inputs.environment }}
