name: build-images

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true
    secrets:
      dockerhub_token:
        required: false
      dockerhub_username:
        required: false
      slack_webhook_url:
        required: true

permissions:
  actions: read
  contents: read
  # to login to aws with oidc
  # https://github.com/aws-actions/configure-aws-credentials#oidc
  id-token: write
  # to be able to add an `auto-merge` label to pr
  issues: write
  # to check which files have been changed in pr and create pr comments
  pull-requests: write

concurrency:
  group: build-images-${{ github.event.number }}-${{ github.event.label.name }}
  cancel-in-progress: true

jobs:
  prepare-input-data:
    runs-on: ${{ inputs.runner }}
    outputs:
      matrix: ${{ steps.data.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Get changed Dockerfiles
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/Dockerfile
      - name: Extract environments from labels and prepare matrix values
        id: data
        run: |
          set -euo pipefail
          # extract environments from pr labels
          # the result will be an array like "dev prod"
          environments=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH" | grep '^build:' | sed 's/^build://')

          # extract the paths to all changed Dockerfiles and add them to the `matrix` variable,
          # which looks like this:
          # {
          #   "include": [
          #     {"environment": "dev", "context": "buildpacks/backend/builder"},
          #     {"environment": "dev", "context": "buildpacks/backend/runner"},
          #     {"environment": "prod", "context": "buildpacks/backend/builder"},
          #     {"environment": "prod", "context": "buildpacks/backend/runner"}
          #   ]
          # }
          matrix='{"include":[]}'
          modified_files="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          for env in ${environments[@]}; do
            for file in ${modified_files[@]}; do
              context=$(dirname "${file}")
              # add a new element to the matrix with the received relative path to the Dockerfile
              # for each environment
              matrix=$(echo "${matrix}" | jq \
                --arg context "${context}" \
                --arg env "${env}" \
                '.include += [{"environment": $env, "context": $context}]')
            done
          done
          echo "matrix=$(echo ${matrix} | jq -c .)"
          echo "matrix=$(echo ${matrix} | jq -c .)" >> $GITHUB_OUTPUT

  build-images:
    runs-on: ${{ inputs.runner }}
    if: ${{ needs.prepare-input-data.outputs.matrix != '[]' }}
    needs:
      - prepare-input-data
    strategy:
      matrix: ${{ fromJson(needs.prepare-input-data.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build and publish backend buildpack builder image
        uses: saritasa-nest/saritasa-github-actions/.github/actions/build-image@v4.4
        with:
          context: ${{ matrix.context }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dockerhub_username: ${{ secrets.dockerhub_username }}
          environment: ${{ matrix.environment }}
          slack_webhook_url: ${{ secrets.slack_webhook_url }}

  create-pr-comment:
    runs-on: ${{ inputs.runner }}
    if: ${{ !cancelled() && needs.build-images.result != 'skipped' }}
    needs:
      - build-images
      - prepare-input-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download data artifacts data for the PR comment template
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true
          path: pr-comment-data
          pattern: '!*.dockerbuild'
      - name: Create common file with vars for the jinja template
        run: |
          set -euo pipefail
          jq -s \
            --arg author "${{ github.event.sender.login }}" \
            --arg link "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --arg status "${{ needs.build-images.result }}" '
              {
                author: $author,
                images: map(.images) | add,
                link: $link,
                status: $status
              }
          ' pr-comment-data/*.json > pr-comment-data.json
      - name: Generate PR comment from jinja template
        uses: cuchi/jinja2-action@v1.3.0
        with:
          data_file: pr-comment-data.json
          template: .github/actions/build-image/pr-comment-template.j2
          output_file: pr-comment.md
      - name: Create or update a PR comment with docker build results
        uses: edumserrano/find-create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: build-images workflow status
          comment-author: github-actions[bot]
          body-path: pr-comment.md
          edit-mode: append

  add-auto-merge-label:
    runs-on: ${{ inputs.runner }}
    if: ${{ !cancelled() && needs.build-images.result == 'success' }}
    needs:
      - build-images
      - create-pr-comment
    steps:
      - name: Add auto-merge label
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: auto-merge
          type: add
