name: checking secrets and vulnerabilities
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  install-checks-dependencies:
    uses: saritasa-nest/saritasa-github-actions/.github/workflows/install-checks-dependencies.yaml@feature/merge-checks
    with:
      trivy-version: 0.50.1

  secret-checks:
    name: secret-checks
    runs-on: saritasa-rocks-eks
    needs: install-checks-dependencies
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}
      - name: secret checks
        uses: saritasa-nest/saritasa-github-actions/.github/actions/secrets-checks@feature/merge-checks
        with:
          enable-trivy-check: true
          enable-gitleaks-check: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          # https://keys.saritasa.cloud/cred/detail/c6nP9FFoXhtxEjKJADwsYQ/
          gitleaks-license: ${{secrets.GITLEAKS_LICENSE}}
          gitleaks-slack-webhook: ${{secrets.TEST_SLACK_WEBHOOK}}

  vuln-checks:
    name: vuln-checks
    runs-on: saritasa-rocks-eks
    needs: install-checks-dependencies
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}
      - name: vulnerability checks
        uses: saritasa-nest/saritasa-github-actions/.github/actions/vulnerability-checks@feature/merge-checks
        with:
          enable-vulnerability-checks: true
          github-token: ${{secrets.GITHUB_TOKEN}}
